site_name: did
theme: 
  name: material
  features:
    - content.code.copy
    - navigation.sections
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Ubuntu
    code: Roboto Mono

docs_dir: docs
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Usage: usage.md
  - Configuration: configuration.md
  - Testing: testing.md
