name: Pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
    - name: Set up Python
      run: |
        uv python install 3.12
    - name: Install dependencies
      run: uv pip install -e . 
    - name: Run pytest
      run: uv run pytest
